--- # change port
server:
  port: 8088

--- # thymeleaf
spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
    suffix: .html
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ${SPRING_DATASOURCE_URL}
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD}
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: hanuri.website